<a href="https://colab.research.google.com/github/jssaini7815/100-days-of-code/blob/master/Word_Embedding_Technique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Word Embedding Technique using Embedding Layer in Keras **

In [ ]:
## Libraries used Tensorflow 2.0 and keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent=['the glass of milk','the glass of juice','the cupof tea',
      'I am a good boy', 'I am a good developer','understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cupof tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
voc_size=10000

**One Hot Encoding **

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[5204, 4879, 7501, 1838], [5204, 4879, 7501, 1619], [5204, 9041, 5370], [897, 2699, 2047, 7343, 5545], [897, 2699, 2047, 7343, 8997], [3354, 5204, 3772, 7501, 8056], [2843, 2926, 1608, 7343]]


** Word Embedding Representation**

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 

In [10]:
import numpy as np


In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5204 4879 7501 1838]
 [   0    0    0    0 5204 4879 7501 1619]
 [   0    0    0    0    0 5204 9041 5370]
 [   0    0    0  897 2699 2047 7343 5545]
 [   0    0    0  897 2699 2047 7343 8997]
 [   0    0    0 3354 5204 3772 7501 8056]
 [   0    0    0    0 2843 2926 1608 7343]]


In [13]:
dim=15

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[-1.22097358e-02  2.26700418e-02 -2.70888451e-02 -2.32511517e-02
   -1.24950893e-02 -9.45837423e-03  1.58379339e-02  1.37300156e-02
   -1.71389692e-02  2.69625336e-03]
  [-1.22097358e-02  2.26700418e-02 -2.70888451e-02 -2.32511517e-02
   -1.24950893e-02 -9.45837423e-03  1.58379339e-02  1.37300156e-02
   -1.71389692e-02  2.69625336e-03]
  [-1.22097358e-02  2.26700418e-02 -2.70888451e-02 -2.32511517e-02
   -1.24950893e-02 -9.45837423e-03  1.58379339e-02  1.37300156e-02
   -1.71389692e-02  2.69625336e-03]
  [-1.22097358e-02  2.26700418e-02 -2.70888451e-02 -2.32511517e-02
   -1.24950893e-02 -9.45837423e-03  1.58379339e-02  1.37300156e-02
   -1.71389692e-02  2.69625336e-03]
  [-2.09249984e-02  2.60581039e-02  4.05318029e-02  4.58326824e-02
    3.89672183e-02  6.09229878e-03 -3.58733535e-02 -3.64789739e-02
   -3.46089527e-03  3.19344290e-02]
  [ 1.58316232e-02 -8.28944519e-03 -3.73725891e-02  2.36864351e-02
    4.22504209e-02  4.37014177e-03 -6.21162727e-03 -1.46357529e-02
    9.42947716e-

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 5204, 4879, 7501, 1838], dtype=int32)

In [19]:
print(model.predict(embedded_docs[0]))

[[[-0.01220974  0.02267004 -0.02708885 -0.02325115 -0.01249509
   -0.00945837  0.01583793  0.01373002 -0.01713897  0.00269625]]

 [[-0.01220974  0.02267004 -0.02708885 -0.02325115 -0.01249509
   -0.00945837  0.01583793  0.01373002 -0.01713897  0.00269625]]

 [[-0.01220974  0.02267004 -0.02708885 -0.02325115 -0.01249509
   -0.00945837  0.01583793  0.01373002 -0.01713897  0.00269625]]

 [[-0.01220974  0.02267004 -0.02708885 -0.02325115 -0.01249509
   -0.00945837  0.01583793  0.01373002 -0.01713897  0.00269625]]

 [[-0.020925    0.0260581   0.0405318   0.04583268  0.03896722
    0.0060923  -0.03587335 -0.03647897 -0.0034609   0.03193443]]

 [[ 0.01583162 -0.00828945 -0.03737259  0.02368644  0.04225042
    0.00437014 -0.00621163 -0.01463575  0.00942948  0.02508802]]

 [[ 0.04357989 -0.00427421 -0.03404158 -0.03728993 -0.04831053
    0.01585427  0.00803324  0.02517844  0.0479496  -0.04831712]]

 [[-0.03035419 -0.01185557  0.02179586  0.04588876  0.04007402
   -0.0128146  -0.02727087  0.0072